name       : dqlite
version    : 1.8.0
release    : 1
source     :
    - https://github.com/canonical/dqlite/archive/refs/tags/v1.8.0.tar.gz : aca6e2075fb139a56dfed96e363f74d27f6014f9a63297c8c8dfea6cf89d4370
license    : LGPL-3.0-only
homepage   : https://github.com/canonical/dqlite
component  : programming.library
summary    : C library for a replicated SQLite cluster
description: |
    C library that implements an embeddable and replicated SQL database engine with high-availability and automatic failover
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(raft)
    - pkgconfig(sqlite3)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
