name       : dqlite
version    : 1.9.1
release    : 4
source     :
    - https://github.com/canonical/dqlite/archive/refs/tags/v1.9.1.tar.gz : fd3a50f2bc14c0a03163bbed3bc5ca6943df144c502de5b497d3b323c24a6489
license    : LGPL-3.0-only
homepage   : https://github.com/canonical/dqlite
component  : programming.library
summary    : C library for a replicated SQLite cluster
description: |
    C library that implements an embeddable and replicated SQL database engine with high-availability and automatic failover
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(raft)
    - pkgconfig(sqlite3)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
