name       : dqlite
version    : 1.9.0
release    : 2
source     :
    - https://github.com/canonical/dqlite/archive/refs/tags/v1.9.0.tar.gz : b3f23019bcdc030b8f1d97ef585a34b24128414d6c2e79fcf729e053578d80a7
license    : LGPL-3.0-only
homepage   : https://github.com/canonical/dqlite
component  : programming.library
summary    : C library for a replicated SQLite cluster
description: |
    C library that implements an embeddable and replicated SQL database engine with high-availability and automatic failover
builddeps  :
    - pkgconfig(libuv)
    - pkgconfig(raft)
    - pkgconfig(sqlite3)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
